### PR TITLE
Add `sync_dir` input to enable sync specified directory

### PR DESCRIPTION
**Pull request by burmecia**
This PR is to add a new optional input `sync_dir`, which will make it possible to only sync the specified directory. It is empty by default, which means to sync the whole bucket.

### CODE REVIEW

**Review by patrickwyler — APPROVED** [review]
Thank you for your improvements!

**Comment by burmecia** [comment]
thanks for merging, any plans for a new release so we can use it?

**Comment by patrickwyler** [comment]
For now you could use "@main", will create the new release this weekend when I'm at home.

**Comment by patrickwyler** [comment]
I released your changes. See [Release 1.3](https://github.com/patrickwyler/gcs-bucket-sync-action/releases/tag/1.3).

**Pull request merged**
